export { default as Client } from '../structures/Client.js'
export { default as Command } from '../structures/Command.js'
export { default as Event } from '../structures/Event.js'
export { default as Slash } from '../structures/Slash.js'
export { default as SendError } from '../structures/SendError.js'
